### ISSUE TITLE
Switch directive from //go:instrument to something else???

### ISSUE THREAD

**Issue by nikolaydubina** [nikolaydubina/go-instrument#1]
Please leave your feedback, vote, comments, anything if you want to keep it or switch to something else.

I am ok to switch!

Lets collect feedback here!

`//go:instrument`

* ????

`something-else`

* sean from golang-nuts

**Comment by justinfx** [comment]
Maybe a suite of directives like this?

```
//instrument:exclude .*
//instrument:include ^Api.*
```

This would cover your original "skip" functionality by calling it "exclude" instead. But also allow disabling automatic instrumentation for all matching functions/methods and then enabling only a subset. This makes it so a user can choose to flip the mode to only specify a subset to automatically instrument.

**Comment by nikolaydubina** [comment]
Nice! This looks very clear, maybe even better than original. Very likely
will switch to this.

Thanks!
