### ISSUE TITLE
Generated file error

### ISSUE THREAD

**Issue by matino** [nikolaydubina/go-instrument#30]
Hi,

I'm wondering, what's the rationale behind returning an error, in case the file is generated?
https://github.com/nikolaydubina/go-instrument/blob/master/main.go#L60

Shouldn't a log and `return nil` be a better choice here?

**Comment by nikolaydubina** [comment]
yes. good point. no reason to error out here. do you want to make change you suggested? I am happy to merge that PR

**Comment by matino** [comment]
Plz see https://github.com/nikolaydubina/go-instrument/pull/31
