### ISSUE TITLE
Ignore files ignored by build

### ISSUE THREAD

**Issue by davidjwilkins** [nikolaydubina/go-instrument#4]
If a file begins with

```
//go:build ignore
// +build ignore
```

it should be ignored by this tool.  Otherwise these comments get stripped, and obviously that causes issues as now a file which should be ignored during build is not.

We end up with an error like

```
#17 0.634 somepackage/somefile.go:7:2: found packages somepackage (fileA.go) and main (fileB.go) in /app
```

**Comment by nikolaydubina** [comment]
make sense. will add sometime soon

**Comment by nikolaydubina** [comment]
cc: @davidjwilkins
