### ISSUE TITLE
Do not change the indentation

### ISSUE THREAD

**Issue by leonklingele** [nikolaydubina/go-instrument#7]
I ran this tool against some of my code bases using the command provided in the README:

`find . -name "*.go" | xargs -I{} go-instrument -app my-service -w -filename {}`

It seems to change the indentation of various files, even though they are already properly formatted using `go fmt`. A git diff of one of those files:

```diff
index 6da35ba..8c5f832 100644
--- a/defaults.go
+++ b/defaults.go
@@ -10,58 +10,58 @@ import (
 )

 const (
-    logFormatJSON = "json"
+    logFormatJSON   = "json"

-    logTargetStdout = "stdout"
-    logTargetStderr = "stderr"
+    logTargetStdout = "stdout"
+    logTargetStderr = "stderr"

-    logLevelPanic = "panic"
-    logLevelFatal = "fatal"
-    logLevelError = "error"
-    logLevelWarn  = "warn"
-    logLevelInfo  = "info"
-    logLevelDebug = "debug"
-    logLevelTrace = "trace"
+    logLevelPanic   = "panic"
+    logLevelFatal   = "fatal"
+    logLevelError   = "error"
+    logLevelWarn    = "warn"
+    logLevelInfo    = "info"
+    logLevelDebug   = "debug"
+    logLevelTrace   = "trace"
 )

// ...
```

**Comment by nikolaydubina** [comment]
correct. this is expected. comments and formatting are stripped. 

this is known limitation of this tool

hopefully, this can be improved, once Go core team improves comment and formatting handling
